### ISSUE TITLE
Insecure Site

### ISSUE THREAD

**Issue by chipthrasher** [caseif/js.nation#13]
```
Your connection is not private

Attackers might be trying to steal your information from jsn.caseif.net (for example, passwords, messages, or credit cards).
NET::ERR_CERT_COMMON_NAME_INVALID
```

**Comment by caseif** [comment]
Try clearing website data in your browser to see if it resolves the issue.

**Comment by chipthrasher** [comment]
OK!

**Comment by caseif** [comment]
Did this resolve the issue?

**Comment by chipthrasher** [comment]
Nope, sorry! Do you mean Shift-reload? I don't know anything that would be
cleared

**Comment by caseif** [comment]
The hotkey in Chrome is ctrl+shift+del. This should clear data pertaining to automatic HTTPS redirects.

**Comment by chipthrasher** [comment]
OK!

**Comment by chipthrasher** [comment]
Still doesnt work?

**Comment by caseif** [comment]
I'll look further into it next week.

**Comment by chipthrasher** [comment]
More information:


jsn.caseif.net normally uses encryption to protect your information. When Google Chrome tried to connect to jsn.caseif.net this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be jsn.caseif.net, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit jsn.caseif.net right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later

**Comment by caseif** [comment]
Should be fixed within the next hour or two. Sorry for the delay.

**Comment by caseif** [comment]
Resolved.
