### ISSUE TITLE
Particles not Loading

### ISSUE THREAD

**Issue by SteveDog1** [caseif/js.nation#15]
Hello,

With js.nation, when you clone/download the files and open up the index.html, the particles seem to not load their actual pictures, but an opaque box instead. I wasn't sure if anyone else had this problem, or if it was just me and there was a simple browser fix. I have the latest browser of Google Chrome, and the demo even works, but it's just the local file that doesn't render the particles.

Thanks, SteveDog.

EDIT: Here's a picture:
![image](https://user-images.githubusercontent.com/37256750/41120359-4b98a9c4-6a63-11e8-8206-60908da07313.png)

**Comment by caseif** [comment]
I think this has something to do with CORS restrictions with relation to the file:// protocol. I don't remember the exact details since I haven't really looked at this repo in a good while, but any potential fix would require some sort of work around to CORS (which is hard).

**Comment by SteveDog1** [comment]
The file is local and I saw a few others experiencing the same problem. Does it have to be put onto a server for it to function correctly?

**Comment by itsIncept** [comment]
That would probably be a workaround for now, but It I think the end goal should be running it straight through the browser. I dont think this was an issue before so maybe something changed with Chrome's behavior @caseif? Or did we just not notice because we ran it on local servers.

**Comment by SteveDog1** [comment]
I downloaded it a few months ago and it was happening, but I thought it was just my browser or an old download, but I re-downloaded it and made sure I had the up to date browser then I issued it.

**Comment by caseif** [comment]
@itsIncept Nah, I think the problem is limited to the `file://` protocol. Since we tested on local HTTP servers, it was effectively the same configuration as a remote website.

**Comment by caseif** [comment]
The problem appears to be limited to Chrome, where the error is as follows:

```
DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
```

The particles render fine on Firefox and Edge.

**Comment by caseif** [comment]
The issue appears to be limited to Chrome, where the error is as follows:

```
DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
```

The particles render fine on Firefox and Edge.

**Comment by caseif** [comment]
Not really an ideal solution but after looking into it a bit, I'm not sure there's much else we can do. I restricted the hack specifically to the case of running locally through Chrome, so it shouldn't impact any other configuration.

**Comment by itsIncept** [comment]
Okay then so I think Browser Support / Requirments should probably be updated then to avoid future confusion.

**Comment by caseif** [comment]
Eh... This is the only issue in a "supported" browser I'm aware of atm, and the fix is pretty much transparent to the end user. Although, maybe we could add a disclaimer about running from the local filesystem?

**Comment by itsIncept** [comment]
That's what I mean, people are assuming they can just clone/download and then open the index file. Should be something about running on a local server for best results.
